### ISSUE TITLE
/bin/sh: 1: exec: gunicorn: not found

### ISSUE THREAD

**Issue by vingorius** [kamalgill/cloud-starterkit-flask-appengine#5]
> {
 insertId: "5ed5e1ae000b179df7887182"  
 labels: {…}  
 logName: "projects/gentok-272102/logs/stderr"  
 receiveTimestamp: "2020-06-02T05:20:46.934785353Z"  
 resource: {…}  
 textPayload: "/bin/sh: 1: exec: gunicorn: not found"  
 timestamp: "2020-06-02T05:20:46.726941Z"  
}

**Comment by kamalgill** [comment]
See https://cloud.google.com/python/getting-started
