### ISSUE TITLE
500 Server Error, "/bin/sh: 1: exec: gunicorn: not found"

### ISSUE THREAD

**Issue by chuckis** [kamalgill/cloud-starterkit-flask-appengine#7]
I have an error, than running app on Google Cloud Platform
`{
 insertId: "5f57baef000ca0b9aca8e0bf"  
 labels: {…}  
 logName: "projects/elegant-door-288810/logs/stderr"  
 receiveTimestamp: "2020-09-08T17:10:07.829125376Z"  
 resource: {…}  
 textPayload: "/bin/sh: 1: exec: gunicorn: not found"  
 timestamp: "2020-09-08T17:10:07.827577Z"  
}`

**Comment by kamalgill** [comment]
See https://cloud.google.com/appengine/docs/standard/python3/runtime

**Comment by chuckis** [comment]
it works at local machine

**Comment by chuckis** [comment]
> See https://cloud.google.com/appengine/docs/standard/python3/runtime
 Maybe I have some gap in knowledge, but I've done exactly all steps described in README file. 
And of cause I read your's links

**Comment by chuckis** [comment]
I'm sorry, found solution at https://cloud.google.com/python/getting-started 
It's my fault.

**Comment by uncvrd** [comment]
@chuckis what step in `getting-started` helped resolve this issue? I have the same error. I figure that the dependencies aren't installing but according to the docs [here](https://cloud.google.com/appengine/docs/standard/python3/runtime#dependencies):

> During deployment, App Engine uses the Python package manager pip to install dependencies defined in the requirements.txt metadata file located in your project's root directory. You do not need to upload dependencies as App Engine performs a fresh install.

So it should automatically install the `requirements.txt`? What am I missing?

**Comment by chuckis** [comment]
@uncvrd, in my case it was a misunderstanding. I had to run some [commands](https://cloud.google.com/python/getting-started#running-your-app) from the Cloud shell, not my local machine
